#!/bin/bash

if [ ! -d "/opt/egraph-@VERSION@" ]; then
    mkdir -p /opt/egraph-@VERSION@
fi

if [ ! -d "/opt/egraph-data" ]; then
    mkdir -p /opt/egraph-data
    chown -R egraphuser:egraphuser /opt/egraph-data
fi

# Sort out file permissions
if [ ! -h "/opt/egraph" ] ;then
    ln -s /opt/egraph-@VERSION@ /opt/egraph
    chown -R egraphuser:egraphuser /opt/egraph
else
    echo "Switch /opt/egraph to /opt/egraph-@VERSION@ and upgrade manually."
fi

if [ ! -f "/opt/egraph-@VERSION@/releases/@VERSION@/vm.args" ]; then
    echo "Created /opt/egraph-@VERSION@/releases/@VERSION@/vm.args from template"
    cp -p "/opt/egraph-@VERSION@/releases/@VERSION@/vm.args.template" "/opt/egraph-@VERSION@/releases/@VERSION@/vm.args"
else
    echo "/opt/egraph-@VERSION@/releases/@VERSION@/vm.args exists and not modified"
fi

if [ ! -f "/opt/egraph-@VERSION@/releases/@VERSION@/sys.config" ]; then
    echo "Created /opt/egraph-@VERSION@/releases/@VERSION@/sys.config from template"
    cp -p "/opt/egraph-@VERSION@/releases/@VERSION@/sys.config.template" "/opt/egraph-@VERSION@/releases/@VERSION@/sys.config"
else
    echo "/opt/egraph-@VERSION@/releases/@VERSION@/sys.config exists and not modified"
fi

chown -R egraphuser:egraphuser /opt/egraph-@VERSION@

# reload sysctl.d files
echo "reloading sysctl settings after change"
sysctl --system > /dev/null

# Uncomment to allow beam application to bind to lower ports
# sudo setcap CAP_NET_BIND_SERVICE=+eip /opt/egraph-@VERSION@/erts*/bin/beam.smp

